// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhnwitfjetzotntxzhjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRobndpdGZqZXR6b3RudHh6aGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1Nzc3NzEsImV4cCI6MjA1NjE1Mzc3MX0.orXLNwGjjXQiLSpcEom83SPhoeBU8tOTlHX84EzULFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);